README.md

The badge was incorrectly pointing to **master**, it should be **main**.

Update codecov badge to point to main

---

.circleci/config.yml

Adds integration with the `auth0/ship` orb to automatically publish to NPM and GitHub.

Update Circle CI config to incluse auth0/ship

---

.circleci/config.yml

Test github releasing with a different token.
PR will be reverted after merging.

Avoid using publish-gh with node-publish

---

__tests__/plugin.test.ts
src/client.proxy.ts

- made arg passed from client proxy to client optional
- fixes `logout()` thrown an exception when called with no args.
Fixes https://github.com/auth0/auth0-vue/issues/91

FIX logout options not required

---

__tests__/plugin.test.ts
playground/router.ts
src/client.proxy.ts
src/plugin.ts

Removed the `window.location.replaceState()` from the plugin initialization when checking the session.
The browser URL is no longer replaced with `/` when refreshing the browser.
https://github.com/auth0/auth0-vue/issues/88

Refactor history.replaceState usage

---

README.md

Calls out the fact that the order in which the plugins gets registered is important.

Update Readme to mention the order of plugin registration

---

src/plugin.ts
src/utils.ts

There seems to be an issue when setting `this` as the value when calling Vue's `provide`. To solve it, we should bind all methods using `this`.
[Vuex appeared to have solved it in the same way](https://github.com/vuejs/vuex/blob/main/src/store.js#L50).

Bind all methods of Auth0VueClient to this

---

package-lock.json
package.json

Pins browserstack-cypress-cli to 1.8.1 to avoid issues with CI

Pin browserstack-cypress-cli to 1.8.1

---

src/global.ts
typedoc.js

Exports some of the used types from spa-js so that the auth0-vue doc now include them making it easier to determine supported properties.
Also sets the [visibilityFilters](https://typedoc.org/guides/options/#visibilityfilters) property in the typedoc config so that the API reference site now defaults to showing external and inherited properties by default rather than only when asked for, you might need to clear localstorage for the site to see the first time experience of these being toggled off.

Export spa-js types, default docs to show inherited and external

---

__tests__/plugin.test.ts
package-lock.json
package.json
playground/components/Home.vue
src/global.ts
src/index.ts
src/interfaces/auth0-vue-client-options.ts
src/interfaces/auth0-vue-client.ts
src/plugin.ts

Updates spa-js to 2.0.1 so that we pull in the openUrl update, updates the types so that LogoutOptions and RedirectLoginOptions are now from auth0-react and omit the onRedirect property, and also corrects the check around openUrl in light of the changes we made

Update spa-js and omit onRedirect from exported types

---

EXAMPLES.md

Adds an example on how to use the Auth0Client outside of a component, such as with an Axios interceptor.

Add example on accessing Auth0Client outside of a component

---

package-lock.json
package.json

Updates `@auth0/auth0-spa-js` to `1.22.6`, this version is identical to `1.22.5` but includes an update to the development dependency `jsonwebtoken`.
Even though `1.22.5` was not vulnerable for the related [CVE](https://unit42.paloaltonetworks.com/jsonwebtoken-vulnerability-cve-2022-23529/) because of the fact that `jsonwebtoken` is a devDependency of `@auth0/auth0-spa-js`, we are cutting a release to ensure build tools no longer report our SDK as vulnerable to the mentioned CVE.

Upgrade @auth0/auth0-spa-js to 1.22.6

---

README.md

Typedoc changes the structure of some URLs so we need to amend the readme links for that

[SDK-3850] Update links to api reference

---

package.json

Adds the `exports` field to package.json as per https://antfu.me/posts/publish-esm-and-cjs and https://nodejs.org/api/packages.html#conditional-exports. This allow tools such as Nuxt to correctly recognize our bundles.
#197

Add exports field to package.json

---

__tests__/plugin.test.ts
src/index.ts
src/plugin.ts
src/utils.ts

Similar to auth0/auth0-react/pull/507 this adds a conversion of `redirect_uri` on the root of config to `authorizationParams.redirect_uri` to ease the transition for folks who might miss the migration note.
All methods that took a `redirect_uri` have been updated to log a warning and set the property to the new way.

Map redirect_uri on config to authorizationParams

---

__tests__/plugin.test.ts
playground/auth0.ts
playground/components/Error.vue
playground/components/Home.vue
playground/router.ts
src/interfaces/auth0-plugin-options.ts
src/plugin.ts

__checkSession is a private method that is only called when the plugin is being installed.
We should ensure errors are not thrown as that would fail running the application and installing the plugin.
Instead, errors are available using the `errors` property on the plugin.
On top of that, we added the possibility to provide an errorPath to control where the SDK should redirect to when an error occured. If omitted, our SDK will redirect back to `/` when an error occured.
Closes #223

Gracefully handle errors upon plugin installation

---

src/plugin.ts

Using `readonly()` kinda changes the types in such a way that it marks all properties as readonly. Instead of actual IdToken (or User) types, it's actualy using an inline type based on the IdToken (but marking everything as readonly).
This means that the Auth0VueClient interface defined properties such as IdTokenClaims as a `Ref<IdToken | undefined>`, the Auth0VuePlugin has them being inferred to as `DeepReadonly<UnwrapNestedRefs<IdToken>>`, which doesn't always align.
This can become complicated to type properly, while they don't really need to be marked as read-only. 
Dropping the read-only shouldn't cause issues, as they share the same public API:
```ts
const x = ref<IdToken>({__raw: 'abc'});
const xReadOnly = readonly(x);
console.log('raw', { x, xReadOnly }); // Logs x: RefImpl and …
```

Avoid using readonly for public exposed reactive properties

---

package-lock.json
package.json

Bumps SPA-JS to v2.1.2 to include the fix for organizations.
https://github.com/auth0/auth0-spa-js/releases/tag/v2.1.2

bump auth0-spa-js to latest version

---

package-lock.json
package.json
playground/api.ts
src/global.ts
src/guard.ts
src/index.ts
src/interfaces/auth0-vue-client-options.ts
src/interfaces/auth0-vue-client.ts
tsconfig.json
tsconfig.test.json

Correctly export and import types to allow verbatimModuleSyntax
Closes #302

Use export type and import type to allow verbatimModuleSyntax

---

src/index.ts

Use the newer syntax for adding component instance properties. The old syntax has issues on newer versions of vue. See reference.
https://github.com/vuejs/language-tools/issues/4793#issuecomment-2336471084

chore: use declare module 'vue' to fix type issues

---

DEVELOPMENT.md
FAQ.md

Fixes a few minor typos in the Markdown documentation.

chore(docs): Fix minor typos
